
package org.hms4j.example.jaxws.devis.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;
import org.hms4j.example.jaxws.devis.DevisBean;
import org.hms4j.example.jaxws.devis.WebServiceResponse;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "DevisService", targetNamespace = "http://service.devis.jaxws.example.hms4j.org")
@XmlSeeAlso({
    org.hms4j.example.jaxws.devis.ObjectFactory.class,
    org.hms4j.example.jaxws.devis.service.ObjectFactory.class
})
public interface DevisService {


    /**
     * 
     * @param devisBean
     * @return
     *     returns org.hms4j.example.jaxws.devis.WebServiceResponse
     */
    @WebMethod
    @WebResult(name = "traiterDevisReturn", targetNamespace = "http://service.devis.jaxws.example.hms4j.org")
    @RequestWrapper(localName = "traiterDevis", targetNamespace = "http://service.devis.jaxws.example.hms4j.org", className = "org.hms4j.example.jaxws.devis.service.TraiterDevis")
    @ResponseWrapper(localName = "traiterDevisResponse", targetNamespace = "http://service.devis.jaxws.example.hms4j.org", className = "org.hms4j.example.jaxws.devis.service.TraiterDevisResponse")
    public WebServiceResponse traiterDevis(
        @WebParam(name = "devisBean", targetNamespace = "http://service.devis.jaxws.example.hms4j.org")
        DevisBean devisBean);

}
