
package org.hms4j.example.jaxws.devis.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "DevisServiceService", targetNamespace = "http://service.devis.jaxws.example.hms4j.org", wsdlLocation = "file:/D:/Users/deckd/git/hms4j/hms4j-example/hms4j-example-services-module1/devisService-wsdl.xml")
public class DevisServiceService
    extends Service
{

    private final static URL DEVISSERVICESERVICE_WSDL_LOCATION;
    private final static WebServiceException DEVISSERVICESERVICE_EXCEPTION;
    private final static QName DEVISSERVICESERVICE_QNAME = new QName("http://service.devis.jaxws.example.hms4j.org", "DevisServiceService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/D:/Users/deckd/git/hms4j/hms4j-example/hms4j-example-services-module1/devisService-wsdl.xml");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        DEVISSERVICESERVICE_WSDL_LOCATION = url;
        DEVISSERVICESERVICE_EXCEPTION = e;
    }

    public DevisServiceService() {
        super(__getWsdlLocation(), DEVISSERVICESERVICE_QNAME);
    }

    public DevisServiceService(WebServiceFeature... features) {
        super(__getWsdlLocation(), DEVISSERVICESERVICE_QNAME, features);
    }

    public DevisServiceService(URL wsdlLocation) {
        super(wsdlLocation, DEVISSERVICESERVICE_QNAME);
    }

    public DevisServiceService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, DEVISSERVICESERVICE_QNAME, features);
    }

    public DevisServiceService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public DevisServiceService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns DevisService
     */
    @WebEndpoint(name = "devisService")
    public DevisService getDevisService() {
        return super.getPort(new QName("http://service.devis.jaxws.example.hms4j.org", "devisService"), DevisService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns DevisService
     */
    @WebEndpoint(name = "devisService")
    public DevisService getDevisService(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.devis.jaxws.example.hms4j.org", "devisService"), DevisService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (DEVISSERVICESERVICE_EXCEPTION!= null) {
            throw DEVISSERVICESERVICE_EXCEPTION;
        }
        return DEVISSERVICESERVICE_WSDL_LOCATION;
    }

}
